// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2Dm0IRUiUWz_754JvVbnEmEsxX_eoGHM',
    appId: '1:951762315739:web:6b2fa5807bc6f82cac5ffe',
    messagingSenderId: '951762315739',
    projectId: 'pa-5al1-croix-rouge',
    authDomain: 'pa-5al1-croix-rouge.firebaseapp.com',
    storageBucket: 'pa-5al1-croix-rouge.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-VEfGaP-fZQtEjcIBsCiBzp7nHPcS9LI',
    appId: '1:951762315739:android:d94f3dd7321d81efac5ffe',
    messagingSenderId: '951762315739',
    projectId: 'pa-5al1-croix-rouge',
    storageBucket: 'pa-5al1-croix-rouge.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgWl7JVUDZk9UN4l4M3O-7wttLbsDyhZE',
    appId: '1:951762315739:ios:d062d814f3fb6e07ac5ffe',
    messagingSenderId: '951762315739',
    projectId: 'pa-5al1-croix-rouge',
    storageBucket: 'pa-5al1-croix-rouge.appspot.com',
    iosClientId: '951762315739-2229l3qmn51aglemo4fecn71pkqathif.apps.googleusercontent.com',
    iosBundleId: 'com.croix.rouge.croixRougeStorageManagerMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgWl7JVUDZk9UN4l4M3O-7wttLbsDyhZE',
    appId: '1:951762315739:ios:d062d814f3fb6e07ac5ffe',
    messagingSenderId: '951762315739',
    projectId: 'pa-5al1-croix-rouge',
    storageBucket: 'pa-5al1-croix-rouge.appspot.com',
    iosClientId: '951762315739-2229l3qmn51aglemo4fecn71pkqathif.apps.googleusercontent.com',
    iosBundleId: 'com.croix.rouge.croixRougeStorageManagerMobile',
  );
}
